# ---

# # 停止所有服务
# - hosts: ice_via
#   tags:
#     - ice_via_servers
#   tasks:
#     - name: stop ice via
#       shell: "{{ deploy_dir }}/ice_via/bin/stop.sh"
#       register: result
#       changed_when: false
#       failed_when: result.rc != 0
#       when: enable_deploy_ice_via|default(false)

#     - name: wait until the IceGrid port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ ice_grid_port }}"
#         state: stopped
#         msg: "the pump port {{ ice_grid_port }} is not down"
#       when: enable_deploy_ice_via|default(false)

#     - name: wait until the Glacier2 port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ ice_glacier2_port }}"
#         state: stopped
#         msg: "the pump port {{ ice_glacier2_port }} is not down"
#       when: enable_deploy_ice_via|default(false)

#     - name: check service ice via status
#       shell: "{{ deploy_dir }}/ice_via/bin/status.sh"
#       register: check_result
#       when: check_service_status

#     - name: ice via status result
#       debug:
#         msg: check service ice via status result ,its pid is {{check_result.stdout }}
#       when: check_service_status


- name: stop ice via
  hosts: ice_via
  tags:
    - ice_via
  tasks:
    - name: stop ice_via service
      shell: bash {{ deploy_dir }}/{{ice_via_dir_name}}/stop_container.sh {{ item.name }}:{{ item.tag }}
      register: result
      changed_when: false
      failed_when: result.rc != 0
      when: enable_deploy_ice_via|default(false)
      with_items: "{{ ice_via_consul_image }}"



# - name: stop carrier
#   hosts: carrier
#   tags:
#     - carrier
#   tasks:
#     - name: stop carrier
#       shell: bash {{ deploy_dir }}/{{carrier_dir_name}}/stop_container.sh {{ item.name }}:{{ item.tag }}
#       register: result
#       changed_when: false
#       failed_when: result.rc != 0
#       when: enable_deploy_carrier|default(false)
#       with_items: "{{ carrier_image }}"

# - name: stop test
#   hosts: test
#   tags:
#     - test
#   tasks:
#     - name: stop test
#       shell: bash {{ deploy_dir }}/{{test_dir_name}}/stop_container.sh {{ item.name }}:{{ item.tag }}
#       register: result
#       changed_when: false
#       failed_when: result.rc != 0
#       when: enable_deploy_test|default(false)
#       with_items: "{{ test_image }}"

    # - name: wait until the consul http port is down
    #   wait_for:
    #     host: "{{ ansible_host }}"
    #     port: "{{ consul_http_port_self | trim }}"
    #     state: stopped
    #     msg: "the pump port {{ consul_http_port_self | trim }} is not down"
    #   when: enable_deploy_consul|default(false)

    # - name: check service consul status
    #   shell: ps -ef | grep "{{ deploy_dir }}/consul/consul agent -config-file {{ deploy_dir }}/consul/config/consul.json" | grep -v "grep" | awk '{print $2}'
    #   register: check_result
    #   when: check_service_status

    # - name: consul status result
    #   debug:
    #     msg: check service consul status result ,its pid is {{check_result.stdout }}
    #   when: check_service_status