---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/{{consul_dir_name}}"
  - "{{ deploy_dir }}/{{consul_dir_name}}/config"
  - "{{ deploy_dir }}/{{consul_dir_name}}/data-dir"
  - "{{ deploy_dir }}/{{consul_dir_name}}/log"

- name: "copy consul mirror tar file"
  copy:
    src: "{{ downloads_dir }}/{{ item.service }}.tar"
    dest: "{{ deploy_dir }}/{{consul_dir_name}}/{{ item.service }}.tar"
  with_items: "{{ ice_via_consul_image }}"

# 加载镜像tar压缩包 
- name: Load consul image from archive
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    # push: yes
    load_path: "{{ deploy_dir }}/{{consul_dir_name}}/{{ item.service }}.tar"
    # source: load
    # force: yes
  with_items: "{{ ice_via_consul_image }}"

- name: Set facts
  set_fact:
    data_dir: "{{consul_docker_path}}/data-dir"
    log_file: "{{consul_docker_path}}/log/"

- name: "copy configuration file"
  template:
    src: "consul.json.j2"
    dest: "{{ deploy_dir }}/{{consul_dir_name}}/config/consul.json"
    mode: 0600

- name: "copy script"
  copy:
    src: "{{ script_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/{{consul_dir_name}}/{{ item }}"
    mode: 0755
  with_items:
    - stop_container.sh
    - clean_docker.sh

- name: "Generate docker-compose.yml configuration file based on docker-compose.yml.j2 template file"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ deploy_dir }}/{{consul_dir_name}}/config/docker-compose.yml"
    mode: 0600
    backup: yes
