---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/{{test_dir_name}}"
  - "{{ deploy_dir }}/{{test_dir_name}}/config"
  - "{{ deploy_dir }}/{{test_dir_name}}/log"

- name: "copy test mirror tar file"
  copy:
    src: "{{ downloads_dir }}/{{ item.service }}.tar"
    dest: "{{ deploy_dir }}/{{test_dir_name}}/{{ item.service }}.tar"
  with_items: "{{ test_image }}"

# 加载镜像tar压缩包 
- name: Load test image from archive
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    # push: yes
    load_path: "{{ deploy_dir }}/{{test_dir_name}}/{{ item.service }}.tar"
    # source: load
    force: yes
  with_items: "{{ test_image }}"

- name: "copy script"
  copy:
    src: "{{ script_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/{{test_dir_name}}/{{ item }}"
    mode: 0755
  with_items:
    - stop_container.sh

- name: "Generate p1_server_config.json configuration file based on p1_server_config.json.j2 template file"
  template:
    src: "p1_server_config.json.j2"
    dest: "{{ deploy_dir }}/{{test_dir_name}}/config/p1_server_config.json"
    mode: 0600
    backup: yes

- name: "Generate docker-compose.yml configuration file based on docker-compose.yml.j2 template file"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ deploy_dir }}/{{test_dir_name}}/config/docker-compose.yml"
    mode: 0600
    backup: yes
