

log_file: /var/log/docker_install.log

# docker configure
docker:
  users: user1
  registry_mirrors: "https://hub.docker.com/"

docker_required_packages:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "gnupg-agent"
  - "software-properties-common"
  - "python3-pip"
  - "python3-setuptools"
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: deb https://download.docker.com/linux/ubuntu focal stable
docker_packges:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
  - "docker-compose"

bin_dir: "{{ playbook_dir }}/bin"
