# yaml 配置
version: '3.6'
services:
  run_carrier:
    image: "luodahui/carrier:v0.5.0"
    container_name: carrier_service
    restart: always
    network_mode: "host"
    # volumes:
    #   - /home/luodahui/test/ansible-demos/install_docker_ubuntu/conf/carrier.yml:/Carrier/config/carrier.yml
    #   - /home/luodahui/test/ansible-demos/install_docker_ubuntu/conf/p2p_priv_key/p2p_priv_key:/Carrier/config/p2p_priv_key
    #   - /tmp/log/:/Carrier/log/
    #   - /home/luodahui:/Carrier/datadir

    volumes:
      - $PWD/carrier.yml:/Carrier/config/carrier.yml
      - $PWD/p2p_priv_key/p2p_priv_key:/Carrier/config/p2p_priv_key
      # - $PWD/log/:/Carrier/log/
      # - $PWD/datadir:/Carrier/datadir
    command: /Carrier/carrier --config-file /Carrier/config/carrier.yml
